Added translation to Russian
Joystream/joystream-org pull request #370
Opened 2021-07-21 11:13 UTC by OIgnat

Comments to this translation will be published here inside discussion branch: https://github.com/Joystream/community-repo/issues/212

Discord user name: AlexZNet#0968 (for any feedbacks or requests for fixes depending on below points or any other reasons).

1. Some terms, like 'Blockchain developer' that contain well-known definitions are translated leaving those definitions as they are. For example 'Blockchain разработчик'. It is usually called in this way locally and will not make any confusion, but looks familiar to everyone. However, if fully native translation looks better, this could be changed.
1.1. at the same time, 'blockchain' and similar definitions were translated.
1.2. definitions like 'testnet' are used as transliterations, because they are commonly used in community and could be understand better than translating them as 'test network' value. Also, definition is simple enough to be understand even for those who do not know, what 'testnet' is.

2. Unlike English, in Russian there are a couple of ways of addressing people, who read text. Let's imagine, as example 'You' and 'you' (can't be expressed as simple, though) - the last one is more modern and simple approach, that, to my mind, fit Joystream concept, according to what I have read at different pages like branding or about Joustream. But if you think the 1-st, more formal one, is better - I can change that.

3. There are some blocks of text like 'day' and 'days'. In Russian there multiple possible values for multiples - but applying this would need technical improvements on website. So multiples were used in the most common use cases.

4. The names of testnets are left in Latin - because they are original names. At the same time, when used in the meaning of city (like Rome as a city) - they were translated.

5. After setting up website locally and checking how it looks like after translation I noticed that 'Road to mainnet' on landing page is not changed, even being translated in json file. So looks like a hardcoded value.

6. At brand page there are definitions like 'Joysteram Blue' & Gray. As I get, those are namings, so they were left as definitions.

2021-07-22 18:10 UTC, OIgnat commented
Added Ukrainian translation

2021-07-27 13:30 UTC, singulart requested changes
Left some comments

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/token.json
> +        "text": "Нет прямой связи между tJOY и JOY. Мы используем tJOY для моделирования реальных экономических стимулов, присутствующих в основной сети, чтобы способствовать развитию платформы и спо
к реальной работе -> к основной сети

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/token.json
> +        "text": "Мы используем Bitcoin Cash (BCH) в качестве средства оплаты в наших тестнетах. Вы можете обналичить tJOY, сделав перевод на выделенный адрес: <0>5D5PhZQNJzcJXVBxwJxZcsutjKPqUPydrvpu6
средства оплаты -> криптовалюты для вывода средств

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/token.json
> +        "text": "В настоящее время единственный способ обеспечить распределение JOY в основной сети - это качественный вклад в платформу и сообщество через нашу <0>Программу для членов-учредителей</0
ключевых участников

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/token.json
> +      "subtitle": "Токены, отправленные Jsgenesis на обмен, будут утилизированы, т.к. конечная стоимость токенов должна остаться неизменной при таком обмене.",
утилизированы -> сожжены
т.к. -> поэтому

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/sumer.json
> +          "text": "В рамках Sumer мы предоставляем простой встроенный модуль времени выполнения. Это связано с тем, что технические сложности и необходимость компромиссов, в предыдущих итерациях разв
простой встроенный модуль времени выполнения -> исправленный системный компонент по управлению контентом

итерациях развития -> версиях

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/sumer.json
> +          "text": "Мы представляем новую рабочую группу, специализирующуюся на работе с платформамой. Первоначально мы также планировали включить новую роль \"Шлюз\", хотя это не вошло в выпуск Sumer
специализирующуюся на работе с платформамой -> специализирующуюся на функциональных улучшениях платформы

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/sumer.json
> +          "title": "Подключения роли строителя платформы",
Добавить роль "Оператор платформы"

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/sumer.json
> +          "text": "Sumer представляет возможность создавать каналы и видео и управлять ими в Joystream Player, заменяя громоздкий и сложный процесс публикации, который требует работы с интерфейсом ко
теснете - опечатка

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/sumer.json
> +        "text": "Изучи релиз план в том виде, каким он был создан во время планирования и узнавай, как проходила разработка."
Изучите, узнайте

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/sumer.json
> +        "text": "Изучи краткое руководство по тестнету Sumer и его целям."
Изучить

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/sumer.json
> +          "title": "Публикация нового каталога данных",
Каталога контента

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/acropolis.json
> +      "text": "Изучай доступные варианты участия и выбирай те, которые тебе больше всего подходят. Влияй на развитие платформы и зарабатывай при этом реальные деньги.",
Изучить

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/acropolis.json
> +        "text": "Читай спецификацию новых возможностей Acropolis."
Прочесть

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/acropolis.json
> +        "text": "Читай релиз план в том виде, каким он был создан во время планирования и узнавай, как проходила разработка."
Прочесть

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/alexandria.json
> +        "text": "Читай релиз план в том виде, каким он был создан во время планирования и узнавай, как проходила разработка."
Прочесть

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/alexandria.json
> +        "text": "Читай краткое руководство по тестнету Alexandria и его целям."
Прочесть

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/antioch.json
> +        "text": "Читай релиз план в том виде, каким он был создан во время планирования и узнавай, как проходила разработка."
Прочесть

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/antioch.json
> +        "text": "Читай краткое руководство по тестнету Antioch и его целям."
Прочесть

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/athens.json
> +      "text": "Изучай доступные варианты участия и выбирай те, который тебе больше всего подходят. Влияй на развитие платформы и зарабатывай при этом реальные деньги.",
Изучите, выберите, вам, Влияйте, зарабатывайте

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/athens.json
> +        "text": "Читай релиз план в том виде, каким он был создан во время планирования и узнавай, как проходила разработка."
Читайте, узнавайте

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/babylon.json
> +        "text": "Читай релиз план в том виде, каким он был создан во время планирования и узнавай, как проходила разработка."
Читайте, узнавайте

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/babylon.json
> +        "text": "Читай краткое руководство по тестнету Babylon и его целям."
Прочесть

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/constantinople.json
> +        "text": "Читай релиз план в том виде, каким он был создан во время планирования и узнавай, как проходила разработка."
Читайте, узнавайте

2021-07-27 13:30 UTC, singulart commented on src/locales/ru/rome.json
> +      "text": "Изучай доступные варианты участия и выбирай те, которые тебе больше всего подходят. Влияй на развитие платформы и зарабатывай при этом реальные деньги.",
Изучите, выберите, вам, Влияйте, зарабатывайте

2021-07-27 13:30 UTC, singulart requested changes
Left some comments

2021-07-27 15:53 UTC, OIgnat commented on src/locales/ua/about.json
> +{
В ru варианте были плейсхолдер-файлы с английским переводом, поэтому в коммите видно английский-русский в виде изменений в файлах. Украинского перевода не было изначально и это новая папка (ua), которую я добавил, поэтому контент просто виден сам по себе (не с чем сравнивать). Чтобы были отображены изменения можно попробовать сделать коммит папки ua с английским вариантом, а потом поверх него - украинский. Не уверен, что в рамках пулл реквеста сработает, но можно попробовать. Напишите, пожалуйста, как стоит поступить.

2021-07-27 16:16 UTC, OIgnat commented on src/locales/ru/sumer.json
> +          "title": "Подключения роли строителя платформы",
Судя по контексту предыдущих правок, возможно использовать "Разработчик платформы"?

2021-07-27 18:21 UTC, OIgnat commented
Requested changes were applied.
Also I have created 2 commits for Ukrainian translation. 1-st switches uk folder to English files and 2-nd returns Ukrainian back. The purpose of this was to try to make Ukrainian translation being side-by-side with English, so review could be done easier.

2021-07-29 10:04 UTC, singulart reviewed
I have to reject this submission, because the low-effort google e-translations like this one violate the terms of the Bounty.

2021-08-20 12:56 UTC, closed without merging