Added Ru translation for Sumer.json
Joystream/joystream-org pull request #373
Opened 2021-08-02 16:31 UTC by OIgnat

2021-08-15 14:31 UTC, katerina510 requested changes

2021-08-15 14:31 UTC, katerina510 commented on src/locales/ru/sumer.json
> +      "text": "<0>Шумеры являются самой ранней известной цивилизацией в историческом регионе южной Месопотамии</0>, возникшие в эпоху энеолита и ранней бронзы между шестым и пятым тысячелетиями до н.
Шумеры являются самой ранней из известных цивилизаций в историческом регионе Южной Месопотамии, возникшей в эпоху энеолита и ранней бронзы между шестым и пятым тысячелетиями до н.э.

2021-08-17 07:11 UTC, katerina510 requested changes

2021-08-17 07:11 UTC, katerina510 commented on src/locales/ru/sumer.json
> +      "text": "Кроме прочих изменений, выпуск тестнета Sumer вносит серьезные улучшения в процесс загрузки контента через наше приложение для воспроизведения."
релиз тестнета Sumer /* пропустила в прошлый раз. Здесь лучше слово "релиз", далее по тексту мы везде используем его */

2021-08-20 08:22 UTC, katerina510 requested changes

2021-08-20 08:22 UTC, katerina510 commented on src/locales/ru/sparta.json
> +          "text": "В качестве \"медиа-платформы, управляемой пользователями\", наша главная цель - предоставить пользователям возможность избирать <0>членов Совета</0>, которые будут представлять инт
Наша главная цель как медиаплатформы, управляемой пользователями, была в том, чтобы предоставить им возможность избирать членов Совета, которые будут представлять их интересы в повседневной работе.

2021-08-20 08:22 UTC, katerina510 commented on src/locales/ru/sparta.json
> +          "title": "Поддержка критических ошибок на приемлемом уровне",
Поддержание количества критических ошибок на приемлемом уровне

2021-08-20 08:22 UTC, katerina510 commented on src/locales/ru/sparta.json
> +          "text": "Как показывает факт выхода нашей сети из строя, мы не достигли этой цели."
показал

2021-08-20 08:22 UTC, katerina510 commented on src/locales/ru/sparta.json
> +      "title": "Город Sparta",
Город Спарта

2021-08-20 08:22 UTC, katerina510 commented on src/locales/ru/sparta.json
>    }
Помимо военной мощи, она обладала уникальной как для своего времени, так и в сравнении с ее греческими конкурентами четко определенной социальной системой и конституцией.

2021-08-20 09:52 UTC, OIgnat commented on src/locales/ru/sparta.json
> +      "title": "ОТКАЗ СЕТИ",
видимо в самом коде сайта нет обращения к файлу перевода. В локальной копии NETWORK DOWN тоже отображается, несмотря на то, что в файле есть перевод.

2021-08-20 10:05 UTC, OIgnat commented on src/locales/ru/sparta.json
>    }
я бы поставил запятую после "уникальной" и после "конкурентами".

2021-08-20 11:32 UTC, katerina510 commented on src/locales/ru/sparta.json
>    }
1) Существует правило обособления конструкции "как... так и". Об этом можно почитать здесь https://russkiiyazyk.ru/punktuatsiya/zapjatye-kak-tak-i.html.
2) Ставить ли запятую после "конкурентами"? Чтобы это понять, нужно выбросить конструкцию "как... так и" из предложения и посмотреть, что получится. Получим: Помимо военной мощи, она обладала уникальной четко определенной социальной системой и конституцией. "Уникальной" и "четко определенной" здесь неоднородные определения. Следовательно, запятая между ними не нужна. Вот здесь можно почитать про однородные/неоднородные определения. https://licey.net/free/4-russkii_yazyk/40-kurs_russkogo_yazyka_sintaksis_i_punktuaciya/stages/713-232_odnorodnye_i_neodnorodnye_opredeleniya.html#:~:text=%D0%9D%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%81%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%20%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9%2C%20%D0%BD%D0%B5%20%D1%81%D0%B2%D1%8F%D0%B7%D0%B0%D0%BD%D0%BD%D1%8B%D1%85,%D0%BD%D0%B5%D0%BE%D0%B4%D0%BD%D0%BE%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%BC%D0%B8%20%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%D0%BC%D0%B8%20%D0%B7%D0%B0%D0%BF%D1%8F%D1%82%D0%B0%D1%8F%20%D0%BD%D0%B5%20%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%81%D1%8F.

2021-08-20 12:17 UTC, katerina510 requested changes

2021-08-20 12:17 UTC, katerina510 commented on src/locales/ru/token.json
> +        "text": "tJOY можно использовать в наших тестнетах так же, как будущие пользователи платформы Joystream смогут использовать токен JOY в основной сети. Три основных функции tJOY - это стейкинг
KPI tJOY /* хотя очень хочется здесь поставить запятую, по правилам она не нужна...  */

2021-08-20 12:17 UTC, katerina510 commented on src/locales/ru/token.json
> +        "title": "Как обменять tJOY в USD?",
tJOY на USD /* конвертировать в..., обменять на... */

2021-08-20 12:17 UTC, katerina510 commented on src/locales/ru/token.json
> +        "text": "Мы используем Bitcoin Cash (BCH) в качестве криптовалюты для вывода средств в наших тестнетах. Вы можете обналичить tJOY, сделав перевод на специальный адрес для утилизации тестовых
1) для сжигания тестовых токенов
2) после адреса нужна точка - это конец предложения

2021-08-20 12:17 UTC, katerina510 commented on src/locales/ru/token.json
> +        "text": "В настоящее время единственным способом обеспечения аллокации JOY основной сети является внесение качественного вклада в платформу и сообщество посредством нашей <0>программы Ключевы
программы членов-основателей.

2021-08-20 12:17 UTC, katerina510 commented on src/locales/ru/token.json
> +      "subtitle": "Токены, отправленные Jsgenesis на обмен, аннулируются, поэтому конечная стоимость токенов остается неизменной при осуществлении обмена.",
на обмен, сжигаются,

2021-08-20 12:17 UTC, katerina510 commented on src/locales/ru/token.json
> +      "title": "Присоединяйтесь к нашему Discord и изменяйте индустрию онлайн видео сервисов"
онлайн-видеосервисов

2021-08-20 15:33 UTC, katerina510 approved these changes

2021-08-20 15:34 UTC, katerina510 approved these changes

2021-08-20 15:36 UTC, katerina510 approved these changes

2021-08-23 07:05 UTC, katerina510 requested changes

2021-08-23 07:45 UTC, katerina510 requested changes

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +      "title": "ЗАМЕНЕН НА ROME"
ЗАМЕНЕНА /* это про сеть, там network replaced выше */

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +      "text": "<0>Известный своей великолепной архитектурой, Акрополь</0>, вероятно, является самым знаменитым строением Парфенона. Он был построен в честь победы над персидскими завоевателями, и сег
завоевателями и сегодня является /* не нужна запятая. простое предложение с однородными сказуемыми */

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +          "text": "Финальная версия платформы будет содержать множество средств для простого и безопасного обмена как публичной, так и личной информацией между участниками. Форум станет первым шагом,
Финальная версия платформы будет предоставлять множество способов простого и безопасного обмена как публичной, так и личной информацией между участниками.

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +          "text": "Старый узел содержал баги, которые блокировали синхронизацию между клиентами и требовал жестко прописанных зависимостей. Новый - работает как нужно, не требуя строгой иерархии или
1) между клиентами, и требовал /* запятая */
2) Новый работает /* не нужно тире */

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +          "title": "Гарантирование высоких показателей доступности узлов хранилищ",
Обеспечение /* лучше же? */

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +          "text": "Общее впечатление от работы с платформой как создателей, так и потребителей контента, зависит от множества параметров. Но, вероятно, самым важным является то, как хранилище, к кото
1) так и потребителей контента зависит от /* не нужна запятая */

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +          "text": "Несмотря на то, что, на данном этапе, количество контента не так велико, наступит момент, когда дублирование полного набора данных на всех узлах станет невозможным. Транши позволят
Несмотря на то что на данном этапе количество контента /* не нужны запятые. https://russkiiyazyk.ru/punktuatsiya/nesmotrja-na-to-chto-kak-pishetsja-zapjatye.html Читать с середины страницы */

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +      "text": "<0>Акрополь - это цитадель на холме в самом сердце Афин.</0> Он также находился в самом сердце Древней Греции, могущественной цивилизации и империи. Акрополь знаменит своими старинными
1) UNESCO => ЮНЕСКО
2) проблем с релизом Athens
3) несмотря на то что /* не нужна запятая https://russkiiyazyk.ru/punktuatsiya/nesmotrja-na-to-chto-kak-pishetsja-zapjatye.html Читать с середины страницы */

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +        "text": "Прочтите план релиза в том виде, в котором он был составлен на этапе планирования и сравните с тем, как прошла разработка."
на этапе планирования, и сравните

2021-08-23 07:45 UTC, katerina510 commented on src/locales/ru/rome.json
> +        "text": "Прочтите план релиза в том виде, в котором он был составлен на этапе планирования и сравните с тем, как прошла разработка."
на этапе планирования, и сравните

2021-08-23 07:51 UTC, katerina510 requested changes

2021-08-23 07:51 UTC, katerina510 commented on src/locales/ru/acropolis.json
> +      "subtitle": "Цели, изложенные ниже, являются упрощенным перечнем основных результатов в нашем релизе <0>OKR</0>",
результатов нашего релиза

2021-08-23 09:05 UTC, katerina510 requested changes

2021-08-23 09:05 UTC, katerina510 commented on src/locales/ru/acropolis.json
>        "goals": {
Прочтите план релиза в том виде, в котором он был составлен на этапе планирования, и сравните с тем, как прошла разработка /* запятая пропущена */

2021-08-23 09:10 UTC, katerina510 requested changes

2021-08-23 09:10 UTC, katerina510 commented on src/locales/ru/rome.json
>          },
Прочтите план релиза в том виде, в котором он был составлен на этапе планирования, и сравните с тем, как прошла разработка. /* запятая пропущена */

2021-08-23 12:32 UTC, katerina510 approved these changes

2021-08-23 12:33 UTC, katerina510 approved these changes

2021-08-23 12:34 UTC, katerina510 approved these changes

2021-08-23 13:23 UTC, katerina510 requested changes

2021-08-23 13:23 UTC, katerina510 commented on src/locales/ru/alexandria.json
> +      "text": "<0>Александрия была основана примерно в 331 г. до н.э. Александром Македонским.</0> Прежде всего, город был известен Александрийским маяком, одним из семи чудес света, а также огромной
1) Прежде всего город был известен /* "прежде всего" в значении "в первую очередь" не обособляется. https://popravilam.com/blog/042-prezhde-vsego-i-v-pervuju-ochered.html */
2)  и поздней античности Александрия /* не нужна запятая */
3) До завоевания Римом это был /* не нужна запятая */

2021-08-23 15:56 UTC, katerina510 approved these changes

2021-08-23 16:17 UTC, katerina510 requested changes

2021-08-23 16:17 UTC, katerina510 commented on src/locales/ru/antioch.json
> +      "text": "Релиз Antioch направлен на исправление бага, который вызвал разрыв в блокчейне, который, к сожалению, стал причиной прекращения работы предыдущего тестнета."
который вызвал разрыв в блокчейне, ставший, к сожалению, причиной... /* не надо 2 раза "который" */

2021-08-23 16:17 UTC, katerina510 commented on src/locales/ru/antioch.json
> +        "title": "Релиз план",
План релиза

2021-08-23 16:17 UTC, katerina510 commented on src/locales/ru/antioch.json
> +        "text": "Прочтите план релиза в том виде, в котором он был составлен на этапе планирования и сравните с тем, как прошла разработка."
на этапе планирования, и сравните /* запятая */

2021-08-23 16:17 UTC, katerina510 commented on src/locales/ru/antioch.json
> +        "text": "Прочтите краткую информацию о тестнете Antioch и его целям."
и его целях.

2021-08-24 05:54 UTC, katerina510 approved these changes

2021-08-24 15:36 UTC, katerina510 requested changes

2021-08-24 15:36 UTC, katerina510 commented on src/locales/ru/athens.json
> +          "text": "Несмотря на то, что узел хранения уже ранее работал, размещал и распространял контент платформы, он содержал жестко прописанные зависимости и баги, которые препятствовали синхрониз
1) Несмотря на то что /* нет запятой */
2) использовался для размещения и распространения контента

2021-08-24 15:36 UTC, katerina510 commented on src/locales/ru/athens.json
> +          "title": "Одобрение обновлений платформы голосованиями Совета",
Голосование Совета за обновление среды выполнения

2021-08-24 15:36 UTC, katerina510 commented on src/locales/ru/athens.json
> +          "text": "Целью Jsgenesis было создание предложения по <0>обновлению среды выполнения</0> и голосование за него в Совете. Если бы Совет достиг кворума, настройки консенсуса системы были бы о
и мы были вынуждены запустить новую сеть Athens с новым генезисным блоком.

2021-08-24 15:36 UTC, katerina510 commented on src/locales/ru/athens.json
> +      "text": "<0>Афины - столица Греции.</0> Они также были центром Древней Греции, могущественной цивилизации и империи. В городе по-прежнему преобладают достопримечательности V века до н.э, включа
1) V века до н.э., /*перед запятой точка пропущена */
2) в развитии по направлению к современной демократии и верховенству закона.

2021-08-24 15:58 UTC, katerina510 requested changes

2021-08-24 15:58 UTC, katerina510 commented on src/locales/ru/babylon.json
> +          "text": "Это станет первым выпуском нашего веб-приложения для потребителей контента, цель которого - быть значительно эффективнее и удобнее, чем текущая версия Pioneer."
1) первым релизом /* везде переводили как "релиз", лучше везде одинаково */

2021-08-25 10:11 UTC, katerina510 requested changes

2021-08-25 10:14 UTC, katerina510 approved these changes

2021-08-28 06:29 UTC, katerina510 approved these changes

2021-08-28 06:33 UTC, katerina510 approved these changes

2021-08-28 06:34 UTC, katerina510 approved these changes

2021-08-28 06:36 UTC, katerina510 approved these changes

2021-08-28 08:18 UTC, katerina510 requested changes

2021-08-28 08:18 UTC, katerina510 commented on src/locales/ru/get-started.json
> +      "buttonText": "Смотрите подробности в GitHub"
Подробнее в GitHub

2021-08-28 15:23 UTC, katerina510 requested changes

2021-08-28 15:23 UTC, katerina510 commented on src/locales/ru/hydra.json
> +          "text": "Нативная поддержка интерфейсов GraphQL, а также встроенных запросов"
фрагментов /* не самих запросов, а фрагментов. здесь можно почитать про встроенные фрагменты https://habr.com/ru/post/335050/ */

2021-08-28 15:23 UTC, katerina510 commented on src/locales/ru/hydra.json
> +          "text": "Составляйте запросы с широкой поддержкой алгебраических типов данных используя директиву @variant"
данных, используя

2021-08-28 15:23 UTC, katerina510 commented on src/locales/ru/hydra.json
> +      "subtitle": "Чтобы узнать еще больше, воспользуйтесь следующими ссылками для связи с нами.",
с нами /* в конце не нужна точка, хоть в оригинале она и есть. дальше идет список */

2021-08-28 15:23 UTC, katerina510 commented on src/locales/ru/hydra.json
> +          "link": "Перейти к каналу"
Ссылка на канал /* я думаю, так лучше в контексте */

2021-08-30 04:57 UTC, katerina510 approved these changes

2021-08-30 05:12 UTC, katerina510 approved these changes

2021-08-30 05:13 UTC, katerina510 approved these changes

2021-08-30 07:28 UTC, katerina510 requested changes

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +        "link": "Попробуйте Atlas",
Попробовать Atlas /* когда ссылка или кнопка, лучше использовать неопределенную форму глагола */

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +        "link": "Попробуйте Pioneer",
Попробовать /* когда ссылка или кнопка, лучше использовать неопределенную форму глагола */

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +        "text": "Pioneer дает возможность выполнять операции в рамках сообщества, а также управлять им. Голосуйте на выборах, организовывайте сбор средств на собственный проект либо поддерживайте раб
выполнять работу

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +      "title": "Дорожная карта к основной сети",
Путь к основной сети /* Дорожная карта - это немного другое. Это как здесь, например, https://www.dash.org/ru/roadmap/. В виде маршрута с точками. Описывается, что было и что будет сделано, удалось ли сделать в срок то, что запланировано. А у нас на странице просто перечисление тестнетов, которые были. Не указаны достижения, нет информации о будущих разработках. Я не могу назвать это картой. К тому же, карта - это roadmap */

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Sparta наш второй тестнет, в котором представлено множество важных технических улучшений.",
Sparta - наш второй

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Athens наш третий тестнет, в котором представлено множество важных технических улучшений.",
Athens - наш третий

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Acropolis наш четвертый тестнет, в котором представлено множество важных технических улучшений.",
Acropolis - наш четвертый

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Rome наш пятый тестнет, в котором представлено множество важных технических улучшений.",
Rome - наш пятый

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Constantinople наш шестой тестнет, в котором представлено множество важных технических улучшений.",
Constantinople - наш шестой

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Alexandria наш седьмой тестнет, в котором представлено множество важных технических улучшений.",
Alexandria - наш седьмой

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Babylon наш восьмой тестнет, в котором представлено множество важных технических улучшений.",
Babylon - наш восьмой

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Antioch наш девятый тестнет, устраняющий баг, который вызвал разрыв блокчейна в сети Babylon.",
Antioch - наш девятый тестнет, устранивший баг, который вызвал разрыв блокчейна в сети Babylon.

2021-08-30 07:28 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Sumer наш десятый тестнет, представляющий приложение для воспроизведения, которое упрощает загрузку контента.",
Sumer - наш десятый тестнет, представивший приложение для воспроизведения, которое упрощает загрузку контента.

2021-08-30 10:45 UTC, katerina510 requested changes

2021-08-30 10:45 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +        "exit": "Выход представляет собой подход полного прекращения взаимодействия с организационной структурой в пользу присоединения к альтернативной, либо создания собственной альтернативы. Эффек
1) Выход - полное прекращение взаимодействия
2) альтернативной либо создание /* нет запятой, создание */
3) от сравнения затрат на прекращение взаимодействия и присоединения к альтернативе либо создание собственной альтернативы. На сегодняшний день стоимость ухода с платформ очень высока. /* аналог - это то же самое, не нужна запятая перед "либо", создание. Не надо про желание терпеть условия, там не было такого. */

2021-08-30 10:45 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +        "loweredCosts": "Создание платформ на основе открытого исходного кода, протоколов и публичных данных, как в случае с системами на основе технологии блокчейн, может кардинально снизить эту сто
контролируют

2021-08-30 10:45 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +        "competition": "Открытые протоколы и наличие открытых данных приведут к развитию возможностей одновременного участия в нескольких платформах одновременно, даже не переключаясь между ними, что
одновременного участия в нескольких платформах, /* не надо 2 раза "одновременно" */

2021-08-30 10:45 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +        "reusability": "Даже более того, использование открытого исходного кода подразумевает, что все наработки платформы могут быть легко использованы повторно, а так как все организационная структ
1) вся организационная структура
2) являются публичными

2021-08-30 10:45 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +    "ctaText": "В наших планах есть еще много места для участия, поэтому присоединяйтесь, отправив нам <0>email</0> или присоединяйтесь к  <1>Discord</1> или <2>Reddit</2>.",
1) В этом плане есть место и для вашего участия, поэтому...
2) <0>email</0>, /*запятая */

2021-08-30 10:45 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +      "text": "<0>[1] Эрсам, Ф. Токены блокчейна и рассвет децентрализованной бизнес-модели. Medium. 1 августа, 2016.</0><0>[2] Сринивасан Б.С. Мысли о токенах. Medium. 27 мая, 2017.</0><0>[3] Диксон
1) Ф. Эрсам
2) К. Диксон
3) Альберт О. Хиршман
4) Жан-Шарль и Жан Тироль Роше
5) "Журнал Европейской экономической ассоциации" /* https://ru.wikipedia.org/wiki/Journal_of_the_European_Economic_Association */

2021-08-31 05:11 UTC, katerina510 approved these changes

2021-08-31 08:46 UTC, katerina510 requested changes

2021-08-31 08:46 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "title": "2. Как мы используем cookie",
файлы cookie

2021-08-31 08:46 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "content": "Мы используем файлы cookie для следующих целей нашего Сервиса: <0 /><0 /><1><0> Предоставление аналитики </0><0> Настройки торговой площадки </0><0> Постоянное локальное хранилище
1) Настройки хранения /* нет никакой торговой площадки */
2) локальное хранение Ключей и Членства.

2021-08-31 08:46 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "title": "3. cookie сторонних источников",
Сторонние файлы cookie

2021-08-31 08:46 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "content": "В дополнение к нашим собственным файлам cookie мы также используем файлы cookie сторонних сервисов, чтобы собирать статистику использования Сервиса, показывать рекламу в Сервисе и
1) используем сторонние файлы cookie, чтобы
2) Пожалуйста, см. пункт 3 Политики Конфиденциальности

2021-08-31 08:46 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "title": "О ваших cookies",
О Ваших файлах cookie

2021-08-31 08:46 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "content": "Если вы хотите удалить файлы cookie или дать настроить свой браузер на удаление или отказ от файлов cookie, посетите справочные страницы своего браузера.<0 />‍<0 /> Однако вам сле
1) Если Вы
2) Однако Вам следует принять во внимание, что если Вы удалите файлы cookie или откажетесь принимать их, Вы можете потерять доступ к некоторым функциям, которые мы предоставляем. Вы также можете лишиться возможности сохранять свои предпочтения, а некоторые из наших страниц могут отображаться некорректно.

2021-08-31 08:52 UTC, katerina510 approved these changes

2021-08-31 08:52 UTC, katerina510 approved these changes

2021-08-31 12:19 UTC, katerina510 requested changes

2021-08-31 12:19 UTC, katerina510 commented on src/locales/ru/roles.json
> +        "monitorCommuncationChannels": "Следить и контролировать общедоступные каналы связи на предмет соответствия политикам использования, принятым в системе управления",
Следить за каналами публичных коммуникаций и проверять их на предмет соответствия

2021-08-31 12:19 UTC, katerina510 commented on src/locales/ru/roles.json
> +        "collaborate": "Сотрудничать, разрабатывать новые политики, руководствуясь обстоятельствами, которые могут меняться"
Сотрудничать для разработки новых стратегий при изменившихся обстоятельствах

2021-08-31 12:19 UTC, katerina510 commented on src/locales/ru/roles.json
> +        "platformUnderstanding": "Глубокое понимание структуры и функций платформы Joystream",
и функционирования

2021-09-01 07:17 UTC, katerina510 approved these changes

2021-09-01 07:32 UTC, katerina510 approved these changes

2021-09-01 07:33 UTC, katerina510 approved these changes

2021-09-01 11:47 UTC, katerina510 requested changes

2021-09-01 11:47 UTC, katerina510 commented on src/locales/ru/founding-members.json
> +        "text": "<0>Сроки</0><1>Программа членов-учредителей Joystream была официально запущена в феврале 2021 года. Программа перестанет принимать новые заявки на участие и начислять дополнительные
1) гражданами США. </1><1>Перед тем как вас официально примут в программу /* и запятая не нужна http://new.gramota.ru/spravka/punctum?layout=item&id=58_522#:~:text=%D0%9F%D1%80%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D1%87%D0%BD%D1%8B%D0%B5%20%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%2C%20%D0%BF%D1%80%D0%B8%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D1%8F%D0%B5%D0%BC%D1%8B%D0%B5%20%D1%81%D0%BE%D1%8E%D0%B7%D0%BE%D0%BC%20%C2%AB%D0%BF%D0%B5%D1%80%D0%B5%D0%B4,%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%20%D1%81%D0%BB%D0%BE%D0%B2%D0%BE%D0%BC%20%C2%AB%D0%BA%D0%B0%D0%BA%C2%BB). */
2) сообщества достигнет установленного нами порога.
3) В настоящее время отчетные периоды длятся две недели.
4) (github.com/joystream/founding-members), а также наш веб-сайт (www.joystream.org) и блог (blog.joystream.org).
5) После официального получения статуса члена-основателя /* чтобы не повторять "присвоение", "присвоено" */
6) Остальная часть присвоенных вам токенов 
7) выдаваемые в основной сети, могут иметь определенный период вестинга или...
8) Ключи членов-основателей, служащие для запроса доли токенов, не должны передаваться третьим 
9) Если это произойдет, баллы
10) </2><0>Отчет об активности</0><1>
11) отчет о котором был отправлен позже этого срока, не будет
12) Обновления данных правил /* в официальном документе предпочтительнее "данных" */
13) будут выявлены серьезные недочеты, Jsgenesis оставляет за собой право объявить об этом после завершения следующего отчетного периода (\"срока\"), и к последующим срокам
будет применяться новая схема, то есть \"очки\" будут пересчитаны.
 14) установленный по усмотрению Jsgenesis
 15) Остальные же части будут учтены в новых \"сроках\".

2021-09-01 11:47 UTC, katerina510 commented on src/locales/ru/founding-members.json
> +        "incorrectPassword": "Неверный пароль, повторите, пожалуйста!",
Неверный пароль. Пожалуйста, попробуйте снова! /* может, нужно не повторить, а изменить его, если изначально вводили неправильно */

2021-09-01 11:47 UTC, katerina510 commented on src/locales/ru/founding-members.json
> +        "faultyJson": "Json неполный, либо содержит некорректные данные. Попробуйте экспортировать его снова!"
неполный либо содержит

2021-09-02 00:57 UTC, traumschule commented
The master branch updated and a rebase is needed:
https://git.joystreamstats.live/Operations/joystream-org/commits/ru

- `src/locales/ru/founding-members.json`
> "earnMorePoints": "Earn more points?"

- `src/locales/ru/get-started.json`
```
      "bountiesCarousel": {
<<<<<<< HEAD                                                                                                                                                                                                         
        "all": "All",                                                                                                                                                                                                
        "coding": "Coding",                                                                                                                                                                                          
        "design": "Design",                                                                                                                                                                                          
        "marketing": "Marketing",                                                                                                                                                                                    
        "research": "Research",                                                                                                                                                                                      
        "contentCreation": "Content Creation",                                                                                                                                                                       
        "translation" : "Translation"                                                                                                                                                                                
=======                                                                                                                                                                                                              
        "all": "Все",                                                                                                                                                                                                
        "coding": "Код",                                                                                                                                                                                             
        "design": "Дизайн",                                                                                                                                                                                          
        "marketing": "Маркетинг",                                                                                                                                                                                    
        "research": "Исследования",                                                                                                                                                                                  
        "contentCreation": "Создание Контента"                                                                                                                                                                       
>>>>>>> Added translation to Russian                                                                                                                                                                                 
      },
```

2021-09-02 13:08 UTC, katerina510 requested changes

2021-09-02 13:08 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "title": "Разъяснения к бренду",
Суть бренда

2021-09-02 13:08 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "balance": "Наш новый брендинг направлен на поиск баланса между очень упрощенным тоном общения с определенным уровнем символизма, и сложностью современных мировых проблем и технологий.",
между очень простым тоном ообщения с символизмом и сложностью современных мировых проблем и технологий.

2021-09-03 05:54 UTC, katerina510 requested changes

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "visualPresentation": "Чтобы обеспечить наилучшее визуальное представление логотипа, на цифровых устройствах его лучше всего использовать в размерах <0>200 до 500+px</0> в ширину.",
от <0>200 до 500px</0>

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "horizontalNarrow": "Логотип Joystream нельзя сужать до размеров менее чем 100px в цифровом или 20 мм в печатном форматах при горизонтальном использовании.",
форматах в горизонтальном виде.

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "verticalNarrow": "При вертикальном использовании логотип нельзя сужать до размеров менее 70px в цифровом или 15 мм в печатном форматах."
В вертикальном виде логотип

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "blackAndBlue": "Наши основные цвета - черный и синий Joystream Blue, характерный цвет, который помогает акцентировать и привлекает внимание. Белый цвет используется для успокоения взгляда, о
Белый цвет используется для умиротворения

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
>          "blueGrey": "Еще один дополнительный цвет, который можно комбинировать с тремя основными цветами, - это серый с синим оттенком, его назначение сравнимо с белым, но он также дает хороший контр
это серый с синим оттенком. Его назначение сравнимо

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "symbolic": "Они не всегда прямолинейны и часто имеют символическое значение, но помогают сделать акцент на важных элементах.",
Описательные значки не всегда /* а то непонятно, о чем */

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "angle": "Линии имеют угол 45°, они должны иметь ширину 2px и расстояние между ними должно быть 8px в масштабе 100%.",
Линии должны быть под углом 45°,

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "basicStyle": "Системные значки в основном стиле сочетают в себе два цвета: черный и синий Joystream Blue. Их цель - визуально представлять определенные действия на веб-сайте или платформе. О
Основной стиль системных значков подразумевает сочетание двух цветов: черного и синего Joystream Blue.

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
>          "subtleAccents": "По возможности, значки должны иметь тонкие синие вставки, составляющие не более 40% всей площади.",
По возможности значки

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
>          "complex": "Они могут быть довольно сложными с визуальной точки зрения, несмотря на использование только трех цветов и отсутствие градиентов.",
довольно сложными визуально

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "oneCommonVertex": "В шаблонах при соприкосновении должна быть хотя бы одна общая вершина. Однако, они не всегда должны касаться друг друга, но, когда касаются, расстояние между частями всегд
Однако они не всегда

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
> +        "overview": "Наши шрифты просты, понятны и современны. Это отражение нашего бренда и нашего посыла.Мы выбрали подходящие гарнитуры шрифтов из семейства PX Grotesk (обычный, полужирный) и Inte
посыла. Мы выбрали /*пробел пропущен */

2021-09-03 05:54 UTC, katerina510 commented on src/locales/ru/brand.json
>          "mood": "Очень важно настроение, которое передают фотографии. Они непременно должны вызывать чувство доверия, общности и радости. Фотографии должны быть разнообразными, поскольку предназначен
круга пользователей. Их необязательно

2021-09-03 05:56 UTC, katerina510 approved these changes

2021-09-03 05:58 UTC, katerina510 approved these changes

2021-09-03 06:32 UTC, katerina510 requested changes

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
> +      "joinOurDiscord": "Присоединиться в Discord"
в Discord /* кнопка плохо выглядит, слишком много текста. пусть будет просто в Discord */

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
>          },
"text": "Представьтесь в Discord",
          "altText": "Представьтесь в Discord" /* давай без точек */

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
>            "text": "Вносите вклад в проект.",
Вносите вклад в проект:

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
>          "earnPoints": "Зарабатывайте баллы в таблице лидеров.",
Зарабатывайте баллы в таблице лидеров

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
>          "foundingMembersButton": "Очки членов-основателей",
Баллы членов-основателей /* раньше было "баллы" */

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
>          "regularMembersButton": "Очки остальных участников",
Баллы остальных участников

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
>          "fullProgramRules": "Ознакомиться с полными правилами программы"
Подробные правила /* текст не помещается в кнопку */

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/founding-members.json
> +        "text": "Этот отказ от ответственности относится к веб-странице, доступной по адресу <0>www.joystream.org/token</0>, а также ко всем другим веб-страницам, цифровым сервисам или приложениям, о
1) Данный отказ
2) содержащаяся в них информация не предназначены

2021-09-03 06:32 UTC, katerina510 commented on src/locales/ru/general.json
> +    "joinNewsletter": "Подписаться на рассылку",
Подписаться /* а то кнопка плохо выглядит */

2021-09-03 06:54 UTC, katerina510 requested changes

2021-09-03 06:54 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +      "text": "<0><0>Jsgenesis уважает Вашу приватность.</0><1/><1/>Эта Политика Конфиденциальности (\"Политика Конфиденциальности\") и Политика использования файлов cookie (\"Политика использования
Colossus</14> (\"Нода хранения\")

2021-09-03 06:54 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "content": "Используя любое Наше Программное обеспечение, Пользователь принимает настоящую Политику Конфиденциальности. Если Вы действуете от имени другой компании или работодателя, Вы должны
или руководствам к нашему Программному обеспечению.

2021-09-03 06:54 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "content": "Настоящая Политика Конфиденциальности может быть изменена по собственному усмотрению Компании. В случае внесения каких-либо существенных изменений Пользователь будет уведомлен в и
заменяющий Приложение, или новый инструмент

2021-09-03 06:54 UTC, katerina510 commented on src/locales/ru/privacy-policy.json
> +        "content": "Мы используем файлы cookie для следующих целей нашего Сервиса: <0 /><0 /><1><0> Предоставление аналитики </0><0> Настройки хранения </0><0> локальное хранение Ключей и Членства.</
предоставление аналитики </0><0> настройки хранения /* с маленьких букв */

2021-09-03 07:10 UTC, katerina510 requested changes

2021-09-03 07:10 UTC, katerina510 commented on src/locales/ru/get-started.json
>        "councilMemberText": "Члены совета избираются заинтересованными сторонами системы, чтобы действовать в долгосрочных интересах платформы. Они несут ответственность за распределение ресурсов, нан
предложений, позволяющей каждому пользователю выдвигать предложения. /* сделаем текст чуть короче, а то страдает верстка */

2021-09-03 07:10 UTC, katerina510 commented on src/locales/ru/get-started.json
> +      "storageLeadText": "Руководитель службы хранения нанимается непосредственно Советом посредством системы предложений и занимается наймом, увольнением и общим руководством поставщиками хранилищ в
Руководитель службы хранения нанимается напрямую Советом посредством

2021-09-03 07:10 UTC, katerina510 commented on src/locales/ru/get-started.json
> +      "contentCuratorText": "Кураторы контента отвечают за публикацию и мониторинг нового контента в каталоге, а также реагируют на сообщения о спорных публикациях. Они также обязаны обновлять информ
1) содержании контента, обеспечивая точность /* сокращаем для правильной верстки */
2) правильность метаданных. К их задачам относится и помощь /* сокращаем */
3) с которыми взаимодействуют пользователи, для улучшения юзабилити. /* сокращаем */

2021-09-03 07:10 UTC, katerina510 commented on src/locales/ru/get-started.json
> +      "contentCreatorText": "Создатели контента - это те участники платформы, которые решили разместить на платформе оригинальный или сторонний контент, который не запрещен для повторной публикации л
1) Создатели контента - это участники платформы, решившие разместить на платформе оригинальный или сторонний контент, не запрещенный для повторной /* сокращаем */
2) и в настоящее время пощрения не предусмотрены, хотя самые активные /* сокращаем */
3) будут вознаграждены по программе членов-учредителей. /* сокращаем */

2021-09-03 07:15 UTC, katerina510 requested changes

2021-09-03 07:15 UTC, katerina510 commented on src/locales/ru/hydra.json
>        "values": {
по транзакциям или состояниям /* строка 29 */

2021-09-03 07:22 UTC, katerina510 requested changes

2021-09-03 07:22 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +        "infrastructure": "Мы считаем, что технология блокчейн может предоставить организационную и экономическую инфраструктуру, которая поможет в решении обеих проблем. Публичная, проверяемая и неи
составлять суждения, основываясь

2021-09-03 07:22 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +        "reusability": "Даже более того, использование открытого исходного кода подразумевает, что все наработки платформы могут быть легко использованы повторно, а так как вся организационная структ
Более того, использование

2021-09-03 07:22 UTC, katerina510 commented on src/locales/ru/manifesto.json
> +    "ctaText": "В этом плане есть место и для вашего участия, поэтому присоединяйтесь, отправив нам <0>email</0>, или присоединяйтесь к <1>Discord</1> или <2>Reddit</2>.",
отправив нам <0>email</0>, или заходите в <1>Discord</1>

2021-09-03 07:47 UTC, katerina510 requested changes

2021-09-03 07:47 UTC, katerina510 commented on src/locales/ru/about.json
> +      "subtitle": "Команда Jsgenesis является ядром, которое разрабатывает Joystream - платформу на блокчейне с открытым исходным кодом."
разрабатывает Joystream, - платформу /* запятая */

2021-09-03 07:47 UTC, katerina510 commented on src/locales/ru/landing.json
> +          "text": "Зарабатывайте токены основной сети, которая запускается в 2021"
в 2021 г

2021-09-03 07:47 UTC, katerina510 commented on src/locales/ru/landing.json
> +      "subtitle": "Два быстро развивающихся приложения для получения контента и управления.",
управления /* уберем точку */

2021-09-03 08:00 UTC, katerina510 requested changes

2021-09-03 17:58 UTC, katerina510 requested changes

2021-09-03 17:58 UTC, katerina510 commented on src/locales/ru/about.json
> +      "join": "Присоединиться",
Присоединиться к

2021-09-03 18:27 UTC, katerina510 requested changes

2021-09-03 18:27 UTC, katerina510 commented on src/locales/ru/about.json
> +      "subtitle": "Команда Jsgenesis является ядром, которое разрабатывает Joystream - платформу на блокчейне с открытым исходным кодом."
разрабатывает Joystream - платформу

2021-11-02 11:01 UTC, katerina510 requested changes

2021-11-02 11:01 UTC, katerina510 commented on src/locales/ru/giza.json
> +          "text": "В этом выпуске системы каталога контента улучшения будут сфокусированы на реализации определенных предложений сообщества, устранении технических недостатков и внедрении интеграции
Улучшения системы каталога контента в этом релизе будут направлены на реализацию некоторых запланированных инициатив сообщества, устранение технических недостатков и интеграцию с новой системой хранения.

2021-11-02 11:01 UTC, katerina510 commented on src/locales/ru/giza.json
> +      "text": "<0>Район, расположенный на территории нынешней Гизы служил некрополем нескольких фараонов, правивших Древним Египтом во 2-м тысячелетии до нашей эры.</0> Три древних гробницы, построен
1) нынешней Гизы, служил
2) Три древних гробницы, построенных в форме

2021-11-02 11:45 UTC, freakstatic commented
@blrhc @DzhideX this translation was been reviewed please check if everything is ok and merge it please

2021-11-09 10:53 UTC, DzhideX commented
I just wanted to start off by saying great work as this hasn't been a small task at all and there are impressively little problems/bugs that I've come across during my review. :100: 

So, I've tested at `1440px`, `1024px`, `768px` and `375px`. If I haven't made any comment to either one of those for any page, then that means that there isn't anything that needs to be changed there. Also, I will defer to @blrhc for the final decision for all of these.

Firstly, it seems to me that the translations for this [PR](https://github.com/Joystream/joystream-org/pull/389) haven't been done so it'd be great if this could also be done!

Secondly, here are some of the possible problems that need to be fixed to make sure that the `/ru` pages look great on all sizes as well:

**Index page**:
- 1024px:
  - Hero: The "videoplatforma" text is too long while being in one part. It therefore can't wrap into a new line and pushes the image to be super small.
  - EarnTokens: Similar problem here "Зарабатывайте" is too long and pushes the image outside of the div.

**Token**:  
- <500px:
  - There is a problem where the one answer with the long address overflows but this has nothing to do with the translation but rather something that we need to fix on our end.

**Sparta**:
  - general.json: NEW on roleCard hasn't been translated.

**Privacy policy**:
  - Hero: The text "конфиденциальности" is too long and goes off screen.

**Founding Members**:
  - Index:
    - 1440px/1024px/375px:
      - "How to participate": The text in the steps is a bit too long and for the last couple and it results in them being pushed down and looking off.
  - Form:
    - In general doesn't look the best on anything somewhat lower than 768px. This may be unavoidable though..?

**About**:
  - Our Team: Can Martin's job description be changed a little? It's a bit long as is imo..
  - Open Positions (1024px, 375px): Text seems a bit too long, can something be done here?

**Brand**:
  - Guides:
    - 768px: Some of the longer text in the sidebar is px to px close with the content on the right. I'm not sure if there's anything that can be done here though. The smaller screen sizes look fine.

2021-11-10 08:20 UTC, OIgnat commented
Index page:
	- To change "videoplatforma" to some smaller word that could be split, translation was a bit rephrased. 
	- "Зарабатывайте" changed to "Получите" (shorter word), which means "Get", however taking into account content in general and following button the sense remains the same.

Sparta:
	- NEW is translated now. While translating I was thinking about if NEW should be translated, but decided that this looks as exception, because it looks organic and familiar for every russian-speaking person as well. At the same time it contains just 3 letters and this value never changes depending on language rules in different contexts. But translated value looks good as well, so it is translated now.

Privacy policy:
	- "конфиденциальности" changed to "приватности". First variant looks better and more common, but taking into account that it causes issues I think it could be changed.

Founding members:
	- Index - I had to make changes to translation itself without changing the general meaning. Some phrases were made shorter. I checked on 375 - it looks better now.
	- Form - changed it a little bit, looks better now

About:
	- Changed Martin's description a little bit
	- Open positions - fixed

2021-11-10 14:07 UTC, blrhc commented
Thanks for those final changes @OIgnat, I think this definitely meets the required standard from our point of view and will now merge this.

Appreciate your efforts @katerina510 also!

2021-11-10 14:07 UTC, blrhc approved these changes

2021-11-10 14:08 UTC, merged