clarify cashout
Joystream/joystream-org pull request #376
Opened 2021-08-06 12:52 UTC by traumschule

2021-08-08 15:23 UTC, blrhc commented on src/locales/en/token.json
> +        "text": "We use Bitcoin Cash (BCH) as a payment rail on our testnets. You can cashout tJOY by making a transfer to the dedicated burn address: <0>5D5PhZQNJzcJXVBxwJxZcsutjKPqUPydrvpu6HeiBfMae
```suggestion
        "text": "We use Bitcoin Cash (BCH) as a payment rail on our testnets. You can cashout tJOY by making a transfer to the dedicated burn address: <0>5D5PhZQNJzcJXVBxwJxZcsutjKPqUPydrvpu6HeiBfMaeKQu</0> Before doing this, you should set the <0>memo</0> of the key which the transfer is made from to your BCH address. The USD to BCH exchange rate calculated at the moment of sending the BCH. <1/><1/>More information on payouts can be found <2>here</2>."
```

2021-08-08 15:24 UTC, blrhc requested changes
Does this look OK?
@traumschule

2021-09-03 08:45 UTC, traumschule commented
@blrhc Sure!

2022-02-11 10:36 UTC, DzhideX commented
Right now we're actually finishing up the new automated Cashout system and this part will have to be rewritten anyways so I think it's best if we update it as part of the [Cashout UI Implementation PR](https://github.com/Joystream/joystream-org/pull/436).

2022-02-11 10:36 UTC, closed without merging