ES Translation
Joystream/joystream-org pull request #386
Opened 2021-09-04 00:02 UTC by StrowDeATh

2021-09-13 18:20 UTC, UnicFb910 requested changes

2021-09-13 18:20 UTC, UnicFb910 commented on src/locales/es/athens.json
> +        "text": "No se publicaron especificaciones para Athenea."
"text": "No se publicaron especificaciones para Athens."

2021-09-13 18:20 UTC, UnicFb910 commented on src/locales/es/athens.json
> +          "text": "Como una \"plataforma de contenido gobernada por el usuario\", permitir que los usuarios carguen y consuman contenido era un objetivo importante para nosotros."
"text": "Como una \"plataforma de contenido gobernada por el usuario\", permitiendo a los usuarios que carguen y consuman contenido era un objetivo importante para nosotros."

2021-09-13 18:20 UTC, UnicFb910 commented on src/locales/es/athens.json
> +          "text": "La intención era que Jsgenesis creara una propuesta para una <0>actualización del tiempo de ejecución</0> y que el Consejo la votara. Si el Consejo alcanzaba el quórum, las reglas
"text": "La intención era que Jsgenesis creara una propuesta para una <0>actualización del runtime</0> y que el Consejo la votara. Si el Consejo alcanzaba el quórum, las reglas de consenso del sistema se actualizarían automáticamente en tiempo de ejecución. Desafortunadamente, la <1>red Sparta se estrelló</1> antes de llegar a esta fase, y tuvo que empezar Athens como una nueva cadena con un nuevo bloque génesis."

2021-09-13 18:20 UTC, UnicFb910 commented on src/locales/es/athens.json
> +      "title": "Funciones incentivadas para la red de Athens"
"title": "Roles incentivados para la testnet Athens"

2021-09-13 18:20 UTC, UnicFb910 commented on src/locales/es/athens.json
> +      "text": "<0>Atenas es la capital de Grecia.</0> También fue el corazón de la antigua Grecia, una poderosa civilización e imperio. La ciudad sigue dominada por los monumentos del siglo V a.C, co
"text": "<0>Atenas es la capital de Grecia.</0> También fue el corazón de la antigua Grecia, una poderosa civilización e imperio. La ciudad sigue dominada por los monumentos del siglo V a.C, como la Acrópolis, una ciudadela en la cima de una colina coronada por edificios antiguos como el templo del Partenón con sus columnas. <1/><1/>Elegimos el nombre de Atenas porque, al igual que nuestras redes de prueba anteriores, Mesopotamia y Esparta, la importancia histórica de la antigua Atenas en el desarrollo hacia la democracia moderna y el estado de derecho. <1/><1/> <2> <0/> Expora la testnet anterior</2>"

2021-09-21 18:47 UTC, UnicFb910 requested changes

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/babylon.json
> +          "text": "Esta será la versión inicial de nuestro cliente consumidor de contenido, con el objetivo de ser considerablemente más eficaz que la actual experiencia mediática de Pioneer."
"text": "Esta será la versión inicial de nuestro cliente de consumo de contenido, con el objetivo de ser considerablemente más eficaz que la actual experiencia de medios Pioneer."

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/babylon.json
> +          "title": "Se desarrolla el primer Joystream Hydra node son soporte al directorio de contenido ",
"title": "Despliegue del primer nodo Joystream Hydra autoalojado soportando sólo el directorio de contenidos",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/babylon.json
> +      "title": "Funciones incentivadas para la red de Babylon"
"title": "Roles incentivados para la red Babylon"

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/babylon.json
> +      "text": "<0>Babilonia fue la ciudad capital del Imperio Babilónico, un reino en la antigua Mesopotamia hace casi 4000 años.</0> Fue construida a lo largo de las orillas izquierda y derecha del
"text": "<0>Babilonia fue la ciudad capital del Imperio Babilónico, un reino en la antigua Mesopotamia hace casi 4000 años.</0> Fue construida a lo largo de las orillas izquierda y derecha del río Éufrates con terraplenes empinados para contener las inundaciones estacionales del río. <1/><1/> La ciudad se considera de gran importancia histórica y cultural. Los Jardines Colgantes de Babilonia fueron una de las Siete Maravillas del Mundo Antiguo y Babilonia también fue supuestamente el sitio de la Torre de Babel.<1/><1/><2><0/> Leer el artículo del blog</2>"

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +      "blogPostCovers": "ortadas de los Blogs",
"blogPostCovers": "Portadas de los Blogs",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "overview": "Vista General",
"overview": "Resumen",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "primaryColors": "Colores primarios",
"primaryColors": "Colores Primarios",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "supportivePallet": "Paleta de colores de apoyo",
"supportivePallet": "Paleta de apoyo",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "secondaryPallet": "Paleta de colores secundarios",
"secondaryPallet": "Paleta secundaria",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "descriptiveIcons": "Iconos descriptivo",
"descriptiveIcons": "Iconos Descriptivos",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "systemIcons": "Iconos del sistema",
"systemIcons": "Iconos del Sistema",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "illustrations": "Ilusytraciones",
"illustrations": "Ilustraciones",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "patterns": "Patrones",
"patterns": "Modelos",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "safeUse": "El uso del logo pequeño",
"safeUse": "El uso seguro más pequeño",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "visualPresentation": "Para garantizar la mejor presentación visual del logotipo, lo mejor es ofrecerlo en tamaños entre <0>200 y 500+px</0> de ancho en dispositivos digitales.",
"visualPresentation": "Para garantizar la mejor presentación visual del logotipo, se ofrece mejor en tamaños entre <0>200 y 500+px</0> de ancho en dispositivos digitales.",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "horizontalNarrow": "El logotipo de Joystream nunca debe ser más estrecho que 100px en digital o 20mm en impresión horisontal.",
"horizontalNarrow": "El logotipo de Joystream nunca debe ser más estrecho que 100px en digital o 20mm en el bloqueo horizontal de la impresión.",

2021-09-21 18:47 UTC, UnicFb910 commented on src/locales/es/brand.json
> +        "title": "03. Paleta de colores secundarios",
"title": "03. Paleta de colores Secundaria",

2021-09-25 14:12 UTC, UnicFb910 requested changes

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +          "text": "Contribuye al proyecto",
"text": "Realiza contribuciones al proyecto",

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +          "contributions": "<0><0>eseñando a otros participantes</0><0>escribir blogs y documentos</0><0>crear y publicar contenido</0><0>participar en las funciones de la plataforma en la red de pru
"contributions": "<0><0>enseñando a otros participantes</0><0>escribiendo blogs y documentos</0><0>creando y publicando contenido</0><0>participando en las funciones de la plataforma en la red de pruebas</0><0>encontrando e informando fallos y errores</0><0>completando las tareas oficiales</0><0>trabajo creativo y de calidad</0></0>"

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +        "report": "Inforar regularmente de tus actividades.",
"report": "Informa regularmente de tus actividades.",

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +        "earnPoints": "Gana puntos en la tabla de cllasificación.",
"earnPoints": "Gana puntos en la tabla de clasificación.",

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +        "becomeFM": "Hagase socio fundador!",
"becomeFM": "Conviértete en socio fundador!",

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +        "initialTokenPool": "tamaño de la circulación inicial de tokens",
"initialTokenPool": "tamaño de la reserva inicial de tokens",

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +        "leaderboards": "Tabla de clasificación",
"leaderboards": "Tablas de clasificación",

2021-09-25 14:12 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +        "foundingMembersButton": "Todo los puntos de los miembros fundadores",
"foundingMembersButton": "Todas la puntuaciones de los miembros fundadores",

2021-09-27 18:29 UTC, UnicFb910 requested changes

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/founding-members.json
> +      "dropFile": "Envíe su archivo aquí o <0>busque archivo</0>",
"dropFile": "Arrastre su archivo aquí o <0>busque un archivo</0>",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "finished": "Red en vivo"
"finished": "Red activa"

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "launchedOn": "Lanzamiento el"
"launchedOn": "Lanzado el"

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "activeRoles": "Funciones activadas",
"activeRoles": "Roles activos",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "upcomingRoles": "Próximas funciones",
"upcomingRoles": "Próximos roles",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "viewAllRoles": "Ver todas las funciones"
"viewAllRoles": "Ver todos los roles"

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "downloadAssets": "Descargar activos",
"downloadAssets": "Descargar medios",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "title": "Manténgase al día",
"title": "Mantente al día",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "alternateTitle": "Reciba notificaciones",
"alternateTitle": "Ser notificado",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "subtitle": "¡No te preocupes por el spam! Manténgase al tanto de todas las actualizaciones importantes",
"subtitle": "¡No te preocupes por el spam! Mantente al tanto de todas las actualizaciones importantes",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "inputPlaceholder": "Correo electronico...",
"inputPlaceholder": "Correo electrónico...",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "joinNewsletter": "Únase al boletín de noticias",
"joinNewsletter": "Únete al boletín de noticias",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +      "repository": "Registro"
"repository": "Respositorio"

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +      "hiring": "¡Estamos contrtando!",
"hiring": "¡Estamos contratando!",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/general.json
> +    "scoringForm": "ormulario de puntuación",
"scoringForm": "Formulario de puntuación",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "title": "Como empezar",
"title": "Cómo empezar",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "description": "Conozca cómo contribuir y participar en el proyecto Joystream"
"description": "Conoce cómo contribuir y participar en el proyecto Joystream"

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "subtitle": "Lea más sobre las formas actuales de añadir valor al proyecto y ganar recompensas por hacerlo.",
"subtitle": "Leer más acerca de las formas actuales de añadir valor al proyecto y ganar recompensas por hacerlo.",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "discord": "Únase a nuestro Discord",
¡"discord": "Únete a nuestro Discord",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "tokens": "Reciba tokens de nuestra testnet gtaris",
"tokens": "Recibe tokens de la testnet gratis",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "membership": "Crear afiliación en la cadena",
"membership": "Crear membresía on-chain",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "opportunities": "Elija una de las siguientes actividades"
"opportunities": "Elije una de las siguientes actividades"

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +        "text": "Las bonificacionesse dan por hacer tardeas que cualquiera puede intentar abordar a cambio de alguna recompensa. Son creadas por Jsgenesis o por el Consejo.",
"text": "Las bonificacionesse dan por realizar tareas que cualquiera puede intentar abordar a cambio de alguna recompensa. Son creadas por Jsgenesis o por el Consejo.",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +        "coding": "Codificador",
"coding": "Programador",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +        "research": "Investiga",
"research": "Investigación",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +      "title": "Funciones activas en la red de pruebas actual",
"title": "Roles activos en la red de pruebas actual",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +        "title": "Funciones",
title": "Roles",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/get-started.json
> +        "text": "Nuestra actual red de pruebas también le permite participar en algunas de las funciones de la plataforma que estarán disponibles en la red principal.<0/><0/>La participación en estas
"text": "Nuestra actual red de pruebas también le permite participar en algunos de los roles de la plataforma que estarán disponibles en la red principal.<0/><0/>La participación en estos roles se recompensa con tJOY (nuestro token de la testnet), que está respaldado por las reservas fiat de Jsgenesis y es canjeable por bitcoin cash.",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +      "title": "Hydra - Un marco para nodos de solicitud del substrato",
"title": "Hydra - Un framework de nodos de consulta, de Substrate",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +      "title": "Hydra - Un marco para nodos de solicitud del substrato",
"title": "Hydra - Un framework de nodos de consulta, de Substrate",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +      "subtitle": "Construir grandes aplicaciones hablando directamente con un nodo completo de Substrate es imposible, y simplemente intentarlo es lento y difícil.",
"subtitle": "Construir grandes aplicaciones hablando directamente con un nodo completo de Substrate es imposible, y intentarlo simplemente es lento y difícil.",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
>            "text": "Your chain may have transactional or state commitments to free-text data, but doing real full-text search client-side is not an option."
"text": "Su cadena puede tener compromisos transaccionales o de estado con datos de texto libre, pero hacer una verdadera búsqueda de texto completo en el lado del cliente no es una opción."

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +          "title": "Procesamiento",
"title": "Filtrado",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +          "text": "Cualquier campo de entidad puede utilizarse para el procesamiento de OpenCRUD"
"text": "Cualquier campo de entidad puede utilizarse para el filtrado OpenCRUD"

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +      "title": "Comience a utilizar Hydra ahora!",
"title": "¡Empieza a utilizar Hydra ahora!",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +      "subtitle": "Utilice los siguientes enlaces para conectarse con nosotros y obtener más información.",
"subtitle": "Utiliza los siguientes enlaces para conectarse con nosotros y obtener más información.",

2021-09-27 18:29 UTC, UnicFb910 commented on src/locales/es/hydra.json
> +          "link": "Ir a la zona de juegos"
"link": "Ir al patio de juegos"

2021-12-21 19:00 UTC, UnicFb910 requested changes
Fixed some translations

2022-02-07 11:17 UTC, DzhideX requested changes
In general, I have to say you've done a really great job as it mostly looks good all around. Assuming the translations are correct there are only really a couple things that I found that I'd want you to fix before we can merge this:

1. The formatting change for `giza.json`  in the `/en` folder aren't really necessary. Could we revert that?
2. Some styling changes:

- footer:
  - join the newsletter button (can we rewrite this somehow?)
  
- alexandria:
  - hero text not translated
    
- babylon:
  - map text wasn't written well (missing text, formatting seems wrong [missing bold text], missing link)
  
- brand/guides
  -`brand.guides.general.(supportivePallete | secondaryPallete)` missing
  
- get-started
  - active roles section: content curator text too long
  - active roles section: storage lead title too long on mobile (is it possible to change somehow?)
  
- giza:
  - hero title not translated (I think?)
  - weird hanging "r" next to link in map section

- token:
  - token in numbers: supply not translated

2024-03-21 17:37 UTC, closed without merging